### ISSUE TITLE
merge httpc with httpx

### ISSUE THREAD

**Issue by gonzaloserrano** [socialpoint-labs/bsk#8]
Even the latter has not been introduced yet when doing so I would merge both. Some types should be renamed (e.g `Decorator`) but I think it's worth doing.

**Comment by ronnylt** [comment]
I think this is a good idea as both packages are extending the `net/http` package. 

Do you have any proposal for the naming of the decorator  types for both cases (client and handlers)?

**Comment by gonzaloserrano** [comment]
`ClientDecorator` and `HandlerDecorator`.

**Comment by gonzaloserrano** [comment]
Example: https://github.com/socialpoint-labs/bsk/pull/10
